### ISSUE TITLE
date not advancing at passing of 24hrs

### ISSUE THREAD

**Issue by PaulskPt** [pimoroni/rv3028-python#11]
Hi (again). Today I got the rv3028-python and i2device-python (slightly modified) working with a RPi Pico on a pico explorer pack. I also created three small functions to facilitate in a yearday function (including check and correction for a leap year). The date and time are now displayed on the small display of the pico explorer pack. The only problem that I encountered is that at the passing of midnight (24hrs) the date doesn't advance. What could be a reason for that?

**Comment by Gadgetoid** [comment]
Poked @rabid-inventor about this, because I did a cursory check through the application manual and can't see anything that might *disable* date auto-increment. Do you have a link to the code you're using?

**Comment by PaulskPt** [comment]
Hi Gadgetoid, thank you for your rapid reply. I copied the files that I use to a folder in my Dropbox. Here is the link: https://www.dropbox.com/sh/0krrd68szhfih0b/AABvheVZk2YxXe-V7vVIhujja?dl=0. The rv3028-python and the i2device-python I cloned from here and https://github.com/pimoroni/i2cdevice-python. Since my post above, until we find a solution to my post above, I added a functionality into my test script to advance the date at the passing of midnight (including checks for month, year passing and leap year situation. The script is in the folder. In the folder is also a just finished .pdf with a description of the experiments I did with a few images.

**Comment by PaulskPt** [comment]
Is there any news after a week?

**Comment by PaulskPt** [comment]
I think I found the solution by doing the following: 
bsos = rtc.get_battery_switchover() # battery switchover status (bsos)
if bsos.find('level_switching_mode') == -1:
    rtc.set_battery_switchover('level_switching_mode')  # Switches RTC to backup battery if VCC goes below 2V
bsos = None

Now the rtc is continuing while normal power is not connected and increasing the time and date correctly.

Case closed!
