### ISSUE TITLE
Install "RTC RV3028 Breakout" on Raspberry Pi 4 on Android

### ISSUE THREAD

**Issue by cantoux** [pimoroni/rv3028-python#12]
Hello,

How can I install "RTC RV3028 Breakout" on Raspberri Pi 4 ?
My Raspberry Pi runs on Android 11 (version Omnirom). 

Thanks a lot :-)

Best Regards,
Cantoux

**Comment by Gadgetoid** [comment]
We don't support Android I'm afraid- I'm going to take an educated guess that the entire software stack would have to be different and there just aren't enough hours in the day to deal with that.

**Comment by cantoux** [comment]
Ok, thanks.
