### ISSUE TITLE
examples/set-time.py throwing error

### ISSUE THREAD

**Issue by orbrey** [pimoroni/rv3028-python#2]
Running ./set-time.py throws up:
"AttributeError: 'datetime.time' object has no attribute 'day'"
Issue is that line 27 reads 'rtc_time = rtc.get_time()'
This should be updated to 'rtc_time = rtc.get_time_and_date()' which will resolve the problem (thanks Sandy!)

Cheers.

**Comment by Gadgetoid** [comment]
I believe this is fixethed!
