### ISSUE TITLE
Wrong datetime from rtc!

### ISSUE THREAD

**Issue by Nic2012** [pimoroni/rv3028-python#5]
Installed a fresh OpenWrt 19.07 and rv3028-python on a PI3, date command returns:
`Sun Jul 21 18:32:11 GMT 2019`

But python set-time.py returns me wrong date fom rtc
```
The time is: 18:35:30 on :01/07/2019
The time is: 18:35:31 on :01/07/2019
```
When I change the original set-time script e.g.
`rtc.set_time_and_date( (2019, 7, 15, 20, 40, 00) )` it returns
`The time is: 20:40:00 on :15/07/2019`

but `rtc.set_time_and_date( (2019, 7, 20, 20, 40, 00) )` returns an error
```
Traceback (most recent call last):
  File "set-time.py", line 25, in <module>
    rtc_time = rtc.get_time_and_date()
  File "/usr/lib/python2.7/site-packages/rv3028-0.0.2-py2.7.egg/rv3028/__init__.py", line 342, in get_time_and_date
ValueError: day is out of range for month
```
and rtc.set_time_and_date( (2019, 7, 21, 20, 40, 00) ) returns again
`The time is: 20:40:00 on :01/07/2019`

rtc.set_time_and_date((2019, 12, 31, 23, 59, 59))
The time is: 23:59:59 on :11/02/2019
The time is: 00:00:00 on :01/01/2020
The time is: 00:00:01 on :01/01/2020
...

**Comment by Nic2012** [comment]
Same problems on a fresh installation Raspbian Buster and a Pi Zero:
```
python3 set-time.py 
set-time.py - Sets RTC with current time for your system and
enables battery backup to preserve the time when power is off.
...
The time is: 10:11:31 on :02/07/2019
The time is: 10:11:32 on :02/07/2019
...
```

**Comment by Nic2012** [comment]
At least a workaround by Unix time works fine :) changed the code to
```
now = datetime.datetime.now().timestamp()
rtc.set_unix_time(int(now))
print(now)

ux = rtc.get_unix_time()
print("get_unix_time:", ux)
print("strftime:", datetime.datetime.fromtimestamp(ux).strftime('%Y-%m-%d %H:%M:%S') )
```
returns
```
1563785780.493591
get_unix_time: 1563785780
strftime: 2019-07-22 10:56:20
```

PS: Add a hint to readme that a dependency is needed when runnning test unit:
`pip install mock`
But this test result wont give any exceptions or hints about mentioned malfunction :(

**Comment by Gadgetoid** [comment]
This is one of those single-bit-flip bugfixes- we'd missed the 6th bit for the BCD coded day of the month.

You should be able to grab the fix with a `git pull origin master` and install by re-running the installer.
