### ISSUE TITLE
Bug with month register

### ISSUE THREAD

**Issue by fabiox23** [pimoroni/rv3028-python#8]
Hi, I believe there is a little bug on line 70 of the __init__.py file.

The mask should be 0b00011111 instead of 0b00001111.

This is causing month 'October' to become '0' when reading the date which would produce an error by the Python interpreter (month outside the range 1..12). Also 'November' would become '1' (January) and 'December' would become '2' (February).

I was going crazy! I didn't understand as to why all of a sudden the library wouldn't work anymore. Luckily, it's an easy fix!

https://github.com/pimoroni/rv3028-python/blob/dabe3bb73d39ef9581a3b3981de2a26168399884/library/rv3028/__init__.py#L70

**Comment by Gadgetoid** [comment]
Ah, BCD strikes again! Good spot, thank you.

Indeed the datasheet confirms this so I'll make and ship the quick tweak post haste.

**Comment by Gadgetoid** [comment]
Hopefully fixed with v0.0.5! Thanks again.
